## Imports

In [1]:
import pandas as pd
import os as os
import gc
import numpy as np

## Data Import

In [2]:
#Simple import
def simple_load_data(in_path, name):
    df = pd.read_csv(in_path)
    print(f"{name}: shape is {df.shape}")
    print(df.info())
    display(df.head(5))
    return df

In [3]:
def load_data(in_path, name):
    early ={'Change_Type': 'object',
            'Covered_Recipient_Type': 'object',
            'Teaching_Hospital_CCN': 'float64',
            'Teaching_Hospital_ID': 'float64',
            'Teaching_Hospital_Name': 'object',
            'Physician_Profile_ID': 'float64',
            'Physician_First_Name': 'object',
            'Physician_Middle_Name': 'object',
            'Physician_Last_Name': 'object',
            'Physician_Name_Suffix': 'object',
            'Recipient_Primary_Business_Street_Address_Line1': 'object',
            'Recipient_Primary_Business_Street_Address_Line2': 'object',
            'Recipient_City': 'object',
            'Recipient_State': 'object',
            'Recipient_Zip_Code': 'object',
            'Recipient_Country': 'object',
            'Recipient_Province': 'object',
            'Recipient_Postal_Code': 'object',
            'Physician_Primary_Type': 'object',
            'Physician_Specialty': 'object',
            'Physician_License_State_code1': 'object',
            'Physician_License_State_code2': 'object',
            'Physician_License_State_code3': 'object',
            'Physician_License_State_code4': 'object',
            'Physician_License_State_code5': 'object',
            'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name': 'object',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID': 'int64',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name': 'object',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State': 'object',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country': 'object',
            'Total_Amount_of_Payment_USDollars': 'float64',
            'Date_of_Payment': 'object',
            'Number_of_Payments_Included_in_Total_Amount': 'int64',
            'Form_of_Payment_or_Transfer_of_Value': 'object',
            'Nature_of_Payment_or_Transfer_of_Value': 'object',
            'City_of_Travel': 'object',
            'State_of_Travel': 'object',
            'Country_of_Travel': 'object',
            'Physician_Ownership_Indicator': 'object',
            'Third_Party_Payment_Recipient_Indicator': 'object',
            'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value': 'object',
            'Charity_Indicator': 'object',
            'Third_Party_Equals_Covered_Recipient_Indicator': 'object',
            'Contextual_Information': 'object',
            'Delay_in_Publication_Indicator': 'object',
            'Record_ID': 'int64',
            'Dispute_Status_for_Publication': 'object',
            'Product_Indicator': 'object',
            'Name_of_Associated_Covered_Drug_or_Biological1': 'object',
            'Name_of_Associated_Covered_Drug_or_Biological2': 'object',
            'Name_of_Associated_Covered_Drug_or_Biological3': 'object',
            'Name_of_Associated_Covered_Drug_or_Biological4': 'object',
            'Name_of_Associated_Covered_Drug_or_Biological5': 'object',
            'NDC_of_Associated_Covered_Drug_or_Biological1': 'object',
            'NDC_of_Associated_Covered_Drug_or_Biological2': 'object',
            'NDC_of_Associated_Covered_Drug_or_Biological3': 'object',
            'NDC_of_Associated_Covered_Drug_or_Biological4': 'object',
            'NDC_of_Associated_Covered_Drug_or_Biological5': 'object',
            'Name_of_Associated_Covered_Device_or_Medical_Supply1': 'object',
            'Name_of_Associated_Covered_Device_or_Medical_Supply2': 'object',
            'Name_of_Associated_Covered_Device_or_Medical_Supply3': 'object',
            'Name_of_Associated_Covered_Device_or_Medical_Supply4': 'object',
            'Name_of_Associated_Covered_Device_or_Medical_Supply5': 'object',
            'Program_Year': 'int64',
            'Payment_Publication_Date': 'object'}
    late = {'Change_Type': 'object',
            'Covered_Recipient_Type': 'object',
            'Teaching_Hospital_CCN': 'float64',
            'Teaching_Hospital_ID': 'float64',
            'Teaching_Hospital_Name': 'object',
            'Physician_Profile_ID': 'float64',
            'Physician_First_Name': 'object',
            'Physician_Middle_Name': 'object',
            'Physician_Last_Name': 'object',
            'Physician_Name_Suffix': 'object',
            'Recipient_Primary_Business_Street_Address_Line1': 'object',
            'Recipient_Primary_Business_Street_Address_Line2': 'object',
            'Recipient_City': 'object',
            'Recipient_State': 'object',
            'Recipient_Zip_Code': 'object',
            'Recipient_Country': 'object',
            'Recipient_Province': 'object',
            'Recipient_Postal_Code': 'object',
            'Physician_Primary_Type': 'object',
            'Physician_Specialty': 'object',
            'Physician_License_State_code1': 'object',
            'Physician_License_State_code2': 'object',
            'Physician_License_State_code3': 'object',
            'Physician_License_State_code4': 'object',
            'Physician_License_State_code5': 'object',
            'Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name': 'object',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID': 'int64',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name': 'object',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State': 'object',
            'Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country': 'object',
            'Total_Amount_of_Payment_USDollars': 'float64',
            'Date_of_Payment': 'object',
            'Number_of_Payments_Included_in_Total_Amount': 'int64',
            'Form_of_Payment_or_Transfer_of_Value': 'object',
            'Nature_of_Payment_or_Transfer_of_Value': 'object',
            'City_of_Travel': 'object',
            'State_of_Travel': 'object',
            'Country_of_Travel': 'object',
            'Physician_Ownership_Indicator': 'object',
            'Third_Party_Payment_Recipient_Indicator': 'object',
            'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value': 'object',
            'Charity_Indicator': 'object',
            'Third_Party_Equals_Covered_Recipient_Indicator': 'object',
            'Contextual_Information': 'object',
            'Delay_in_Publication_Indicator': 'object',
            'Record_ID': 'int64',
            'Dispute_Status_for_Publication': 'object',
            'Related_Product_Indicator': 'object',
            'Covered_or_Noncovered_Indicator_1': 'object',
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1': 'object',
            'Product_Category_or_Therapeutic_Area_1': 'object',
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1': 'object',
            'Associated_Drug_or_Biological_NDC_1': 'object',
            'Covered_or_Noncovered_Indicator_2': 'object',
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2': 'object',
            'Product_Category_or_Therapeutic_Area_2': 'object',
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2': 'object',
            'Associated_Drug_or_Biological_NDC_2': 'object',
            'Covered_or_Noncovered_Indicator_3': 'object',
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3': 'object',
            'Product_Category_or_Therapeutic_Area_3': 'object',
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3': 'object',
            'Associated_Drug_or_Biological_NDC_3': 'object',
            'Covered_or_Noncovered_Indicator_4': 'object',
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4': 'object',
            'Product_Category_or_Therapeutic_Area_4': 'object',
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4': 'object',
            'Associated_Drug_or_Biological_NDC_4': 'object',
            'Covered_or_Noncovered_Indicator_5': 'object',
            'Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5': 'object',
            'Product_Category_or_Therapeutic_Area_5': 'object',
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5': 'object',
            'Associated_Drug_or_Biological_NDC_5': 'object',
            'Program_Year': 'int64',
            'Payment_Publication_Date': 'object'}
    old_format = ['2013', '2014', '2015']
    if(name in old_format):
        col_map = early
    else:
        col_map = late
    df = pd.read_csv(in_path, dtype = col_map)    
    if(name in old_format):
        df = adjust_cols(df)
    obj_cols = df.select_dtypes('O').columns
    for col in obj_cols:
        df[col] = df[col].astype('category')
    print(f"{name}: shape is {df.shape}")
    #print(df.info())
    display(df.head(5))
    #df['Year'] = name
    return df

In [4]:
def adjust_cols(df):
    #merge device and drug columns - then drop them
    for i in range(1,6):
        first = f'Name_of_Associated_Covered_Drug_or_Biological{i}'
        second = f'Name_of_Associated_Covered_Device_or_Medical_Supply{i}'
        col_name = f'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_{i}'
        df[col_name] = df[first] + '--' + df[second]
        df = df.drop(columns = [first, second])

    #Rename columns to know 
    re_col = {'Product_Indicator': 'Related_Product_Indicator',
              'NDC_of_Associated_Covered_Drug_or_Biological1': 'Associated_Drug_or_Biological_NDC_1',
              'NDC_of_Associated_Covered_Drug_or_Biological2': 'Associated_Drug_or_Biological_NDC_2',
              'NDC_of_Associated_Covered_Drug_or_Biological3': 'Associated_Drug_or_Biological_NDC_3',
              'NDC_of_Associated_Covered_Drug_or_Biological4': 'Associated_Drug_or_Biological_NDC_4',
              'NDC_of_Associated_Covered_Drug_or_Biological5': 'Associated_Drug_or_Biological_NDC_5'}
    df = df.rename(columns = re_col)
    return df

In [5]:
%%time
DATA_DIR = 'Data/General/'

datasets = {} # lets store the datasets in a dictionary so we can keep track of them easily
ds_names = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']

for ds_name in ds_names:
    datasets[ds_name] = load_data(os.path.join(DATA_DIR, f'OP_DTL_GNRL_PGYR{ds_name}_P06302020.csv'), ds_name)
    print('Imported: ', ds_name)

2013: shape is (4172205, 60)

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,...,Associated_Drug_or_Biological_NDC_3,Associated_Drug_or_Biological_NDC_4,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
0,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,251792.0,LAURA,E,SCHANBERG,NaN,...,NaN,NaN,NaN,2013,06/30/2020,NaN,NaN,NaN,NaN,NaN
1,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,221879.0,JENNIFER,J,BUCKI,NaN,...,NaN,NaN,NaN,2013,06/30/2020,NaN,NaN,NaN,NaN,NaN
2,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,293260.0,JOEL,M,KREMER,NaN,...,NaN,NaN,NaN,2013,06/30/2020,NaN,NaN,NaN,NaN,NaN
3,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,358533.0,MITCHELL,A,LAZAR,NaN,...,NaN,NaN,NaN,2013,06/30/2020,NaN,NaN,NaN,NaN,NaN
4,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,181904.0,DOMENICO,NaN,ACCILI,NaN,...,NaN,NaN,NaN,2013,06/30/2020,NaN,NaN,NaN,NaN,NaN

Imported:  2013
2014: shape is (11318435, 60)

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,...,Associated_Drug_or_Biological_NDC_3,Associated_Drug_or_Biological_NDC_4,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
0,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,70745.0,ROBERT,NaN,DAVIS,NaN,...,NaN,NaN,NaN,2014,06/30/2020,NaN,NaN,NaN,NaN,NaN
1,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,331070.0,JAMES,NaN,NAIRUS,NaN,...,NaN,NaN,NaN,2014,06/30/2020,NaN,NaN,NaN,NaN,NaN
2,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,65541.0,HEATHER,NaN,KILLIE,NaN,...,NaN,NaN,NaN,2014,06/30/2020,NaN,NaN,NaN,NaN,NaN
3,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,177950.0,THOMAS,NaN,MARKS,NaN,...,NaN,NaN,NaN,2014,06/30/2020,NaN,NaN,NaN,NaN,NaN
4,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,336513.0,SAREH,NaN,PARANGI,NaN,...,NaN,NaN,NaN,2014,06/30/2020,NaN,NaN,NaN,NaN,NaN

Imported:  2014
2015: shape is (11561896, 60)

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,...,Associated_Drug_or_Biological_NDC_3,Associated_Drug_or_Biological_NDC_4,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5
0,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,136242.0,MARK,RAYMOND,LINDSEY,NaN,...,NaN,NaN,NaN,2015,06/30/2020,NaN,NaN,NaN,NaN,NaN
1,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,1245686.0,BEVERLY,JEAN,TALBERT,NaN,...,NaN,NaN,NaN,2015,06/30/2020,NaN,NaN,NaN,NaN,NaN
2,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,1189163.0,ABHILASH,P,NAMBIAR,NaN,...,NaN,NaN,NaN,2015,06/30/2020,NaN,NaN,NaN,NaN,NaN
3,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,904296.0,LUQMAN,K,DAD,NaN,...,NaN,NaN,NaN,2015,06/30/2020,NaN,NaN,NaN,NaN,NaN
4,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,705877.0,DANIEL,NaN,DORTON,NaN,...,NaN,NaN,NaN,2015,06/30/2020,NaN,NaN,NaN,NaN,NaN

Imported:  2015
2016: shape is (11697166, 75)

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,...,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date
0,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,1206885.0,Richard,G,Wunderink,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,06/30/2020
1,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,351732.0,ADEL,NaN,ABADIR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,06/30/2020
2,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,351732.0,ADEL,NaN,ABADIR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,06/30/2020
3,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,351732.0,ADEL,NaN,ABADIR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,06/30/2020
4,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,319082.0,JAMAL,ZIAD,ABDIN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,06/30/2020

Imported:  2016
2017: shape is (11395407, 75)

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,...,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date
0,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,1300911.0,MARION,NaN,ANTHONY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,06/30/2020
1,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,113198.0,ELISABETH,NaN,ANTON,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,06/30/2020
2,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,924405.0,PETER,H,AHN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,06/30/2020
3,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,924405.0,PETER,H,AHN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,06/30/2020
4,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,780716.0,DAVID,B,MANSUR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,06/30/2020

Imported:  2017
2018: shape is (10897848, 75)

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,...,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date
0,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,299919.0,KEITH,A,VASENIUS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,06/30/2020
1,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,154298.0,EDWARD,NaN,LOGUE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,06/30/2020
2,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,122437.0,SENTHIL,K,THAMBIDORAI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,06/30/2020
3,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,105088.0,AZRA,S,AYUBI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,06/30/2020
4,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,464937.0,Hatice,NaN,Savas,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,06/30/2020

Imported:  2018
2019: shape is (10367307, 75)

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,...,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date
0,NEW,Covered Recipient Physician,NaN,NaN,NaN,827477.0,STEPHEN,W.,BOATRIGHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,06/30/2020
1,NEW,Covered Recipient Physician,NaN,NaN,NaN,623090.0,JASON,NaN,FOREMAN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,06/30/2020
2,NEW,Covered Recipient Physician,NaN,NaN,NaN,3362255.0,MAURICE,NaN,HAMAOUI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,06/30/2020
3,NEW,Covered Recipient Physician,NaN,NaN,NaN,3362255.0,MAURICE,NaN,HAMAOUI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,06/30/2020
4,NEW,Covered Recipient Physician,NaN,NaN,NaN,3362255.0,MAURICE,NaN,HAMAOUI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,06/30/2020

Imported:  2019
Wall time: 37min 14s

## General Count Data

In [31]:
years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']
int_year = [None] * len(years)
total = [None] * len(years)
total_paid = [None] * len(years)
docs = [None] * len(years)
comp = [None] * len(years)

for i, year in enumerate(years):
    int_year[i] = int(year)
    total[i] = datasets[year].shape[0]
    total_paid[i] = np.round(datasets[year]['Total_Amount_of_Payment_USDollars'].sum(), 2)
    docs[i] = datasets[year]['Physician_Profile_ID'].nunique()
    comp[i] = datasets[year]['Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name'].nunique()

counts_dict = {'Year': int_year,
               'Total': total,
               'Total_Paid': total_paid,
               'Doctors': docs,
               'Company_Count': comp}

counts = pd.DataFrame.from_dict(counts_dict)
counts

   Year     Total    Total_Paid  Doctors  Company_Count
0  2013   4172205  1.016570e+09   480741           1399
1  2014  11318435  2.700300e+09   624712           1595
2  2015  11561896  2.739472e+09   636383           1593
3  2016  11697166  2.906662e+09   637824           1598
4  2017  11395407  2.939390e+09   633437           1580
5  2018  10897848  3.059756e+09   629364           1648
6  2019  10367307  3.563597e+09   613924           1564

In [35]:
counts.to_csv('Data/Output/counts.csv', index = False)

## Aggregate by Payment Amount

In [7]:
def agg_by_payment(group_col, col_names):
    years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']
    #states = [None] * len(years)
    agg_op_features = {'Total_Amount_of_Payment_USDollars': ['sum', 'count', 'mean']}
    agg_df = pd.DataFrame()
    for i, year in enumerate(years):
        if 'NA' not in datasets[year][group_col].cat.categories:
            datasets[year][group_col] = datasets[year][group_col].cat.add_categories('NA').fillna('NA')
        st = datasets[year].groupby(group_col).agg(agg_op_features)
        st['Year'] = int(year)
        st.columns = st.columns.map('_'.join)
        st = st.reset_index()
        if(agg_df.empty):
            agg_df = st
        else:
            agg_df = agg_df.append(st)
    agg_df['Total_Amount_of_Payment_USDollars_mean'] = np.round(agg_df['Total_Amount_of_Payment_USDollars_mean'], 2)
    agg_df['Total_Amount_of_Payment_USDollars_sum'] = np.round(agg_df['Total_Amount_of_Payment_USDollars_sum'], 2)
    agg_df.columns = col_names
    agg_df.head(15)
    return agg_df

### State

In [15]:
state = agg_by_payment('Recipient_State', ['State', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
state.to_csv(f'Data/Output/states.csv', index = False)

In [ ]:
states = pd.read_csv(state_url)
states_new = states.merge(id_df, left_on = 'State', right_on = 'state', how = 'left')
states_new = states_new.drop(columns = ['state'], axis = 1)
states_new.to_csv('Data/Output/states.csv')
states_nona = states_new[states_new['id'].notna()]
states_nona.loc[:,'id'] = states_nona.loc[:,'id'].astype('int64')
states_nona.to_csv('Data/Output/states_nona.csv')
states_nona_2013 = states_nona[states_nona['Year'] == 2013]
states_nona_2013.to_csv('Data/Output/states_nona_2013.csv')

In [ ]:
pops = pd.read_csv('Data/Output/pops.csv')
pop_melt = pd.melt(pops, id_vars = ['NAME'], value_vars = ['2013', '2014', '2015', '2016', '2017', '2018', '2019'],
                  var_name = 'Pop', value_name = 'Year')
abr = pd.read_csv('Data/Output/abbrev.csv')
abr.drop(['Abbrev'], axis = 1, inplace = True)
ps = pop_melt.merge(abr, left_on = 'NAME', right_on = 'State', how = 'left')
ps.drop(['NAME'], axis = 1, inplace = True)
states_names = states_nona.merge(ps, left_on = ['State', 'Year'], right_on = ['Code','Year'], how = 'inner')
states_names.drop(['Code'], axis = 1, inplace = True)
states_names.rename(columns = {'State_x': 'State', 'State_y': 'Name'}, inplace = True)
states_names['Sum_pc'] = np.round((states_names['Payment_Sum'] / states_names['Pop']) * 10000, 2)
states_names['Count_pc'] = np.round((states_names['Payment_Count'] / states_names['Pop']) * 10000, 2)
states_names['Mean_pc'] = np.round((states_names['Payment_Mean'] / states_names['Pop']) * 10000, 2)
states_names.to_csv('Data/Output/states_pc.csv', index = False)
states_names

### Zip Code - Long and Short Form

In [16]:
#Create a column with just 5 digit zips
years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']
for year in years:
    datasets[year]['Five_Zip'] = datasets[year]['Recipient_Zip_Code'].astype(str).str[:5]
    datasets[year]['Five_Zip'] = datasets[year]['Five_Zip'].astype('category')
    
zipcode_long = agg_by_payment('Recipient_Zip_Code', ['Zip', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
zipcode_long.to_csv(f'Data/Output/zip_codes_long.csv', index = False)

zipcode_short = agg_by_payment('Five_Zip', ['Zip', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
zipcode_short.to_csv(f'Data/Output/zip_codes_short.csv', index = False)

### Physician Type (MD, DO, etc.)

In [17]:
p_type = agg_by_payment('Physician_Primary_Type', ['Physician_Type', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
p_type.to_csv(f'Data/Output/phys_type.csv', index = False)

### Physician_Specialty

In [18]:
p_spec = agg_by_payment('Physician_Specialty', ['Physician_Spec', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
p_spec.to_csv(f'Data/Output/phys_spec.csv', index = False)

### Manufacturer

In [19]:
manu = agg_by_payment('Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name', ['Manufacturer', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
manu.to_csv(f'Data/Output/manufacturer.csv', index = False)

### Date (might be silly or interesting)

In [20]:
date = agg_by_payment('Date_of_Payment', ['Date', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
date.to_csv(f'Data/Output/date_agg.csv', index = False)

### Agg by month

In [ ]:
date_agg = pd.read_csv(date_url)
date_agg.head()
date_agg.dropna(axis = 0, inplace = True)
date_agg['Date'] = pd.to_datetime(date_agg['Date'], format = '%m/%d/%Y')
date_agg = date_agg.set_index(pd.DatetimeIndex(date_agg['Date']))
h = date_agg.groupby(date_agg['Date'].dt.strftime('%B %Y'))['Payment_Sum', 'Payment_Count'].sum()
h.index = pd.DatetimeIndex(h.index)
h = h.sort_values(by = 'Date')
h['Month'] = h.index.month
h['Year'] = h.index.year
h.to_csv(f'Data/Output/month_agg.csv')
h.head()

### Form of Payment

In [21]:
f_pay = agg_by_payment('Form_of_Payment_or_Transfer_of_Value', ['Form', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
f_pay.to_csv(f'Data/Output/form_pay.csv', index = False)

### Nature of Payment

In [22]:
nat_pay = agg_by_payment('Nature_of_Payment_or_Transfer_of_Value', ['Nature_Pay', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
nat_pay.to_csv(f'Data/Output/nat_pay.csv', index = False)

## Aggregate by Doctor

In [13]:
years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']
phys_info_path = 'Data/Phys_info/OP_PH_PRFL_SPLMTL_P06302020.csv'
phys_cols = ['Physician_Profile_ID', 'Physician_Profile_First_Name', 'Physician_Profile_Middle_Name', 'Physician_Profile_Last_Name', 'Physician_Profile_Suffix',
             'Physician_Profile_Address_Line_1', 'Physician_Profile_Address_Line_2', 'Physician_Profile_City', 'Physician_Profile_State', 'Physician_Profile_Zipcode',
             'Physician_Profile_Country_Name', 'Physician_Profile_Primary_Specialty']
for year in years:
    datasets[year]['Physician_Profile_ID'] = datasets[year]['Physician_Profile_ID'].astype('category')
doc_agg = agg_by_payment('Physician_Profile_ID', ['Doc_ID', 'Payment_Sum', 'Payment_Count', 'Payment_Mean', 'Year'])
phys_info = simple_load_data(phys_info_path, 'phys_info')
phys_info['Physician_Profile_ID'] = phys_info['Physician_Profile_ID'].astype('category')
phys_info = phys_info[phys_cols]
doc_merge = doc_agg.merge(phys_info, left_on = 'Doc_ID', right_on = 'Physician_Profile_ID')
doc_merge.to_csv(f'Data/Output/doc_agg.csv', index = False)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3254: DtypeWarning: Columns (26) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

phys_info: shape is (1086673, 27)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086673 entries, 0 to 1086672
Data columns (total 27 columns):
 #   Column                                   Non-Null Count    Dtype
---  ------                                   --------------    -----
 0   Physician_Profile_ID                     1086673 non-null  int64
 1   Physician_Profile_First_Name             1086655 non-null  object
 2   Physician_Profile_Middle_Name            769188 non-null   object
 3   Physician_Profile_Last_Name              1086639 non-null  object
 4   Physician_Profile_Suffix                 28447 non-null    object
 5   Physician_Profile_Alternate_First_Name   481332 non-null   object
 6   Physician_Profile_Alternate_Middle_Name  353549 non-null   object
 7   Physician_Profile_Alternate_Last_Name    481328 non-null   object
 8   Physician_Profile_Alternate_Suffix       18714 non-null    object
 9   Physician_Profile_Address_Line_1         1086671 non-null  object
 10  Physician_Profile_Address_Line_2         400701 non-null   object
 11  Physician_Profile_City                   1086673 non-null  object
 12  Physician_Profile_State                  1086269 non-null  object
 13  Physician_Profile_Zipcode                1086671 non-null  object
 14  Physician_Profile_Country_Name           1086670 non-null  object
 15  Physician_Profile_Province_Name          402 non-null      object
 16  Physician_Profile_Primary_Specialty      1022897 non-null  object
 17  Physician_Profile_OPS_Taxonomy_1         1080776 non-null  object
 18  Physician_Profile_OPS_Taxonomy_2         182552 non-null   object
 19  Physician_Profile_OPS_Taxonomy_3         40882 non-null    object
 20  Physician_Profile_OPS_Taxonomy_4         13975 non-null    object
 21  Physician_Profile_OPS_Taxonomy_5         6261 non-null     object
 22  Physician_Profile_License_State_Code_1   1086673 non-null  object
 23  Physician_Profile_License_State_Code_2   334776 non-null   object
 24  Physician_Profile_License_State_Code_3   99139 non-null    object
 25  Physician_Profile_License_State_Code_4   29469 non-null    object
 26  Physician_Profile_License_State_Code_5   10513 non-null    object
dtypes: int64(1), object(26)
memory usage: 223.8+ MB
None

,Physician_Profile_ID,Physician_Profile_First_Name,Physician_Profile_Middle_Name,Physician_Profile_Last_Name,Physician_Profile_Suffix,Physician_Profile_Alternate_First_Name,Physician_Profile_Alternate_Middle_Name,Physician_Profile_Alternate_Last_Name,Physician_Profile_Alternate_Suffix,Physician_Profile_Address_Line_1,...,Physician_Profile_OPS_Taxonomy_1,Physician_Profile_OPS_Taxonomy_2,Physician_Profile_OPS_Taxonomy_3,Physician_Profile_OPS_Taxonomy_4,Physician_Profile_OPS_Taxonomy_5,Physician_Profile_License_State_Code_1,Physician_Profile_License_State_Code_2,Physician_Profile_License_State_Code_3,Physician_Profile_License_State_Code_4,Physician_Profile_License_State_Code_5
0,28367,LAURIE,E,GOSSARD,NaN,NaN,NaN,NaN,NaN,625 AFRICA RD STE 200,...,207R00000X,NaN,NaN,NaN,NaN,OH,NaN,NaN,NaN,NaN
1,28418,EUNJIN,HAN,SUH,NaN,NaN,NaN,NaN,NaN,10673 MCSWAIN DR,...,122300000X,NaN,NaN,NaN,NaN,OH,NaN,NaN,NaN,NaN
2,28453,CHESTER,D,ZAHN,NaN,NaN,NaN,NaN,NaN,1026 E LAS TUNAS DR,...,207RG0100X,NaN,NaN,NaN,NaN,CA,MI,NaN,NaN,NaN
3,28510,CONRAD,O,YU,NaN,NaN,NaN,NaN,NaN,7455 W WASHINGTON AVE,...,207X00000X,207XS0106X,NaN,NaN,NaN,MA,NV,NaN,NaN,NaN
4,28518,STEPHEN,F,FRIEDL,NaN,NaN,NaN,NaN,NaN,4047 SALADIN DR SE,...,208600000X,NaN,NaN,NaN,NaN,MI,NaN,NaN,NaN,NaN

## Aggregated by Drug

In [7]:
# count the number of non-nulls
years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']
drug_cols =['Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2',
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3', 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4',
            'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5']
agg_op_features = {'Total_Amount_of_Payment_USDollars': ['sum', 'count', 'mean'],
                   'amount_split': ['sum', 'count', 'mean']}
long = 'Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1'
drug_agg_df = pd.DataFrame()

for year in years:
    if 'drug_count' not in datasets[year]:
        datasets[year]['drug_count'] = datasets[year][drug_cols].notna().sum(axis=1)
    if 'NONE' not in datasets[year][long].cat.categories:
        datasets[year][long] = datasets[year][long].cat.add_categories('NONE')
    datasets[year][long][datasets[year]['drug_count'] == 0] = 'NONE'
    datasets[year]['drug_count'] = datasets[year]['drug_count'].replace(0, 1)
    drug_melt = pd.melt(datasets[year], id_vars = ['Total_Amount_of_Payment_USDollars', 'drug_count', 'Program_Year'], value_vars = drug_cols,
                        var_name = 'Slot', value_name = 'Drug')
    drug_melt['amount_split'] = drug_melt['Total_Amount_of_Payment_USDollars'] / drug_melt['drug_count']
    lel = drug_melt.groupby('Drug', as_index=False).agg(agg_op_features)
    lel.columns = lel.columns.map('_'.join)
    lel['Year'] = year
    if(drug_agg_df.empty):
        drug_agg_df = lel
    else:
        drug_agg_df = drug_agg_df.append(lel)

drug_agg_df.to_csv(f'Data/Output/drug_agg.csv', index = False)

## Heatmap

In [97]:
years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']
heat_df = pd.DataFrame()

for year in years: 
    print(year)
    combo = pd.DataFrame()
    combo['Form'] = datasets[year]['Form_of_Payment_or_Transfer_of_Value']
    combo['Nature'] = datasets[year]['Nature_of_Payment_or_Transfer_of_Value']
    combo = combo.groupby(['Form', 'Nature']).size().reset_index(name='count')
    combo = combo[combo['count'] != 0]
    combo['Year'] = year
    if(heat_df.empty):
        heat_df = combo
    else:
        heat_df = heat_df.append(combo)
    
heat_df.to_csv('Data/Output/heat_agg.csv', index = False)

2013
2014
2015
2016
2017
2018
2019

## Network Graph

In [61]:
cols = ['Recipient_City', 'Recipient_State', 'Recipient_Country', 'City_of_Travel', 'State_of_Travel', 'Country_of_Travel']
trav = datasets['2015'][cols].loc[datasets['2015']['City_of_Travel'].notna() | 
                                  datasets['2015']['State_of_Travel'].notna() | datasets['2015']['Country_of_Travel'].notna()]

In [33]:
t = trav['Country_of_Travel'].value_counts()

In [185]:
years = ['2013', '2014', '2015', '2016', '2017', '2018', '2019']
for year in years:
    trav = datasets[year][cols].loc[datasets[year]['City_of_Travel'].notna() |
                                    datasets[year]['State_of_Travel'].notna() |
                                    datasets[year]['Country_of_Travel'].notna()]
    #Drop any row where the country is US, but state is null. Can't really know what the real state should be in many cases
    #Not dropping many rows at all
    drop_ind = trav[(trav['State_of_Travel'].isnull()) & (trav['Country_of_Travel'] == 'United States')].index
    trav.drop(drop_ind, inplace = True)
    drop_ind2 = trav[(trav['Recipient_State'].isnull()) & (trav['Recipient_Country'] == 'United States')].index
    trav.drop(drop_ind2, inplace = True)
    drop_ind3 = trav[(trav['Recipient_City'].isnull()) & ((trav['Recipient_Country'] != 'United States') | (trav['Recipient_Country'].isnull()))].index
    trav.drop(drop_ind3, inplace = True)
    drop_ind4 = trav[(trav['City_of_Travel'].isnull()) & ((trav['Country_of_Travel'] != 'United States') | (trav['Country_of_Travel'].isnull()))].index
    trav.drop(drop_ind4, inplace = True)
    trav['Recipient_City'] = trav['Recipient_City'].astype(str)
    trav['Recipient_City'] = trav['Recipient_City'].str.upper()
    trav['City_of_Travel'] = trav['City_of_Travel'].astype(str)
    trav['City_of_Travel'] = trav['City_of_Travel'].str.upper()
    trav['Recipient_Country'] = trav['Recipient_Country'].astype(str)
    trav['Recipient_Country'] = trav['Recipient_Country'].str.upper()
    trav['Country_of_Travel'] = trav['Country_of_Travel'].astype(str)
    trav['Country_of_Travel'] = trav['Country_of_Travel'].str.upper()
    trav['Recipient_State'] = trav['Recipient_State'].astype(str)
    trav['State_of_Travel'] = trav['State_of_Travel'].astype(str)
    trav['Source_name'] = ''
    trav['Target_name'] = ''
    trav['Source_name'][trav['Recipient_Country'] == 'UNITED STATES'] = trav['Recipient_City'] + ', ' + trav['Recipient_State']
    trav['Source_name'][trav['Recipient_Country'] != 'UNITED STATES'] = trav['Recipient_City'] + ', ' + trav['Recipient_Country']
    trav['Target_name'][trav['Country_of_Travel'] == 'UNITED STATES'] = trav['City_of_Travel'] + ', ' + trav['State_of_Travel']
    trav['Target_name'][trav['Country_of_Travel'] != 'UNITED STATES'] = trav['City_of_Travel'] + ', ' + trav['Country_of_Travel']
    unique_places = pd.unique(trav[['Source_name', 'Target_name']].values.ravel('K'))
    up_df = pd.DataFrame({'Label': unique_places})
    up_df.index.name = 'Id'
    up_df.to_csv(f'Data/Output/Network/node_{year}.csv')
    up_df.reset_index(level=0, inplace=True)
    trav = trav.merge(up_df, left_on = 'Source_name', right_on = 'Label', how = 'left')
    trav.rename(columns = {'Id': 'Source'}, inplace = True)
    trav = trav.merge(up_df, left_on = 'Target_name', right_on = 'Label', how = 'left')
    source = trav['Source']
    target = trav['Id']
    edge = pd.DataFrame({'Source': source, 'Target': target})
    edge_df = edge.groupby(['Source', 'Target']).size().reset_index(name='Weight')
    same_city = edge_df[edge_df['Source'] == edge_df['Target']]
    same_city.to_csv(f'Data/Output/Network/Extra/same_city_{year}.csv', index = False)
    edge_df = edge_df[edge_df['Source'] != edge_df['Target']]
    edge_df['Type'] = 'Undirected'
    edge_df.to_csv(f'Data/Output/Network/edge_{year}.csv', index = False)